USE [ProLine]

--To rename current report files to latest revision name.
BEGIN
DELETE FROM SGM WHERE SID=40

--Orders
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) VALUES(40000,40,NULL,'New Order Listing','Ord_New',0,'C')
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Expiring Orders Listing','Ord_Expiring',1,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Expired Orders Listing','Ord_Expired',84,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Renewed Orders Listing','Ord_Renewed',2,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Confirmed Proposal Listing','Quote_Conf',80,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Pending Proposal Listing','Quote_Pending',81,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Confirmed Renewal Listing','Renewal_Confirmed',82,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Pending Renewal Listing','Renewal_Pending',83,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Renewals Review','Renewal_Review',38,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Listing By Year','Ord_ByYear',31,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Progress Listing','Ord_Progress',57,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Summary','Ord_Summary',59,'C' FROM SGM WHERE SID=40 AND GID<41000 
--INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Due For Billing Order Listing','Ord_DueBills',3,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Notification Of Fogging To NEA','Ord_FoggNEA',32,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Fire Brigade','Ord_Fogg_FBgde',33,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Warranty To Be Issued Listing','Ord_Warr_ToIssue',44,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Warranty By Format Listing','Ord_Warr_Format',40,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Warranty Expired By Format Listing','Ord_Warr_Expired',42,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Warranty Summary','Ord_Warr_Sum',39,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Certificate Listing','Ord_Cert',41,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Certificate Expiry Listing','Ord_Cert_Expiry',43,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Quotation Listing','Acct_Inv_List',68,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Confirmed Proposal Listing (WQL)','Quote_Confirmed_b',80,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Pending Proposal Listing (WQL)','Quote_Pending_b',81,'C' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Customer Contract History','Ord_New_b',0,'C' FROM SGM WHERE SID=40 AND GID<41000 

--Marketing
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Customers Listing','Cust_List',13,'M' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Customer Mailing Listing','Cust_Mailing',23,'M' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Total Customers In Billing','Cust_TotalBilled',12,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Top Listing Customers','Cust_TopList',11,'M' FROM SGM WHERE SID=40 AND GID<41000 
--INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Customers Listing By D.O.B','Cust_DOB',24,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Prospect Activity Listing','Cont_ProspActv',28,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Birthday Analysis','Cont_BirthAnal',71,'M' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Contact Statistics','Cont_Statistic',72,'M' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Contact List','Cont_List',74,'M' FROM SGM WHERE SID=40 AND GID<41000 

--Operations
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Due Services Listing','Svc_Due',8,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Missed Services Listing','Svc_Missed',9,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Missed Services Chart','Svc_MissedChart',10,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Work Plan Listing','Svc_WorkPlan',14,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'PDA Service Data Tracking','Svc_PDAList',17,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Customer Complaint Listing','Svc_Complaint',18,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Odometer Tracking','Svc_POdometer',19,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Work Type Listing','Svc_WorkType',20,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Productivity Report','Svc_Prodvty',21,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Productivity Report (Monthly)','Svc_ProdvtyMth',21,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Completed Services Listing','Svc_Completed',26,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Total Customers By Zone','Cust_TotalByZone',27,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Missed Services By Zone','Svc_MissedByZone',30,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Service Analysis By Sales','Svc_SalesAnal',45,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Service Analysis By Tech','Svc_TechAnal',45,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Service Form Listing','SForm_List',64,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Service Target Tracking','SForm_Target',65,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Service Item Tracking','SForm_Item',66,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Unscheduled Orders Listing','Ord_Unscheduled',85,'S' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Daily Job Listing','Svc_JobList',86,'SJ' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Travel Analysis','Svc_TravAnal',87,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Daily Schedule Listing','Svc_JobList_d',86,'SJ' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Routine/Inspection Job Listing','Svc_Joblist_c',86,'S' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Complaint/Follow Up Job Listing','Svc_Joblist_b',86,'S' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Missed Job Listing','Svc_Missed_b',86,'S' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Due Job Listing','Svc_Due_b',86,'S' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Items For Service','Job_Items',92,'SJ' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Service Planning','Svc_Planning',93,'SJ' FROM SGM WHERE SID=40 AND GID<41000 

--Accounts
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Debtor Aging Details','Acct_AgingDet_Dbr',4,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Creditor Aging Details','Acct_AgingDet_Crd',4,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Invoice Listing','Acct_Inv_List',68,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Debit/Credit Note Listing','Acct_CNDN_List',68,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Official Receipt Listing','Acct_OReceipt_List',7,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Payment Voucher Listing','Acct_PVoucher_List',22,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Invoice Listing (New Order)','Acct_Inv_NewOrd_List',34,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Unbilled Jobs Listing','Acct_UnbilledJobs',35,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Billing By Status','Ord_BillingStatus',35,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'GST Listing (Invoice)','Acct_InvGST_List',69,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'GST Listing (C/N)','Acct_InvGST_List',69,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Debtor Aging Summary','Acct_AgingSum',52,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Creditor Aging Summary','Acct_AgingSum',52,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Sales & Receipts Listing','Acct_SlsRcpt_List',55,NULL FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Unbilled Orders Listing','Acct_UnbilledOrd',58,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Statement Of Account','Acct_Statement',60,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Ledger Details','Acct_LedgerDetails',61,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Trade Ledger','Acct_TradeLedger',62,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Trial Balance','Acct_TrialBalance',63,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Sales Aging','Acct_SalesAging',7,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Cash Sales','Acct_CS_List',68,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Cash Purchase','Acct_CP_List',68,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Delivery Order','Acct_DO_List',68,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Ledger Details with Grand Total','Acct_LedgerDetails_b',61,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Trade Ledger with Payment References','Acct_TradeLedger_b',62,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Project Costing Listing','Acct_OrdCost_List',90,'A' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Account Reconciliation','Acct_ReconList',94,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Post Dated Payment Aging','Acct_PDPayment',54,'A' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Outstanding List by Month','Acct_OS_List',4,'A' FROM SGM WHERE SID=40 AND GID<41000 

--Stock Control
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Purchase Order Listing','Stk_PurchOrder',68,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Supplier Invoice Listing','Stk_SuppInv',68,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Production Order Listing','Stk_ProdctnOrd',68,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Production Note Listing','Stk_ProdctnNote',68,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock List','Stk_List',155,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Low Level Stocks Listing','Stk_Reorder',153,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Balance','Stk_Balance',150,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Check Listing','Stk_Check',154,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Transaction Listing','Stk_Transactions',151,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Usage','Stk_Usage',152,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Monthly Summary','Stk_Summ',88,'I' FROM SGM WHERE SID=40 AND GID<41000 
--INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Staff Usage (Detailed)','Stk_Usage_Det',153,'I' FROM SGM WHERE SID=40 AND GID<41000 
--INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Staff Usage (Summary)','Stk_Usage_Sum',154,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Card','Stk_Ledger',156,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Usage Details','Stk_Usage_c',152,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Purchase Order Details Listing','Stk_PurchOrder_b',68,'I' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Supplier Invoice Details Listing','Stk_SuppInv_b',68,'I' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Usage By Service','Stk_Transactions_b',151,'I' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Receive Listing','Stk_Usage_d',152,'I' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Card (No Cost)','Stk_Ledger_NC',156,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Balance (No Cost)','Stk_Balance_NC',150,'I' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Summary','Stk_Summ',156,'I' FROM SGM WHERE SID=40 AND GID<41000

--Management
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Audit Trail','Mgmt_Audit_Trail',53,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Security Setting','Mgmt_Sec_Sett',56,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Workflow Tracking','Mgmt_WFlow-Trk',70,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Business Analysis By Industry','Mgmt_Bus_IndAnal',47,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Business Analysis By Order Type','Mgmt_Bus_OrdAnal',47,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Business Analysis By Salesperson','Mgmt_Bus_SalesAnal',47,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Business Analysis By Stock','Mgmt_Bus_StkAnal',49,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Monthly Invoice Analysis','Acct_InvAnal_Mth',37,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Value Details By Target','Ord_ValDet_Target',120,'Z' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Confirmed Proposal Listing (WQR)','Quote_Confirmed_c',80,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Pending Proposal Listing (WQR)','Quote_Pending_c',81,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Yearly Sales By Salesperson','Ord_New_c',0,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Sales Order Report','Ord_New_d',0,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Confirmed Renewal List By Yearly','Renewal_Confirmed_b',82,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Pending Renewal List By Yearly','Renewal_Pending_b',83,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Value By Industry','Ord_Val_Industry',120,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Value By Product','Ord_Val_Product',120,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Value By Sales','Ord_Val_Sales',120,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Value By Target','Ord_Val_Target',120,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Value Details By Industry','Ord_ValDet_Industry',120,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Value Details By Product','Ord_ValDet_Product',120,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Value Details By Sales','Ord_ValDet_Sales',120,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Value Details By Target','Ord_ValDet_Target',120,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Value Revenue Category By Month','Ord_Val_Rev_ByMth',120,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Order Value Portfolio History By Month','Ord_Val_Pfolio_ByMth',120,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Product Sales Record','Ord_ValDet_Sales_b',120,'Z' FROM SGM WHERE SID=40 AND GID<41000 
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Deliverables Report','Mgmt_Deliverables',89,'Z' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Project Progress Report','Mgmt_ProjectProgress',95,'Z' FROM SGM WHERE SID=40 AND GID<41000
INSERT INTO SGM(GID,SID,UGC,[Desc],Abbrev,Val,SCC) SELECT MAX(GID)+1,40,NULL,'Stock Usage With Cost Amount','Stk_Usage_b',152,'Z' FROM SGM WHERE SID=40 AND GID<41000

DELETE FROM SYS WHERE ID LIKE 'Rpt%' AND number=0
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2=56',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Purchase Order Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2=56',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Purchase Order Details Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2 IN(53,54,55)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Supplier Invoice Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2 IN(53,54,55)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Supplier Invoice Details Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2=67',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Production Order Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2=77',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Production Note Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2 IN(50,51,52)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Cash Sales'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2 IN(90,91,92)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Cash Purchase'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2=70 AND TSTD.ID IN(SELECT MIN(TD.ID) FROM TSTF TF INNER JOIN TSTD TD ON TD.TSTFID=TF.ID GROUP BY TF.ID)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Monthly Invoice Analysis'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2=70 AND TSTD.ID IN(SELECT MIN(TD.ID) FROM TSTF TF INNER JOIN TSTD TD ON TD.TSTFID=TF.ID GROUP BY TF.ID)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Invoice Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2 IN(71,72) AND TSTD.OAmt<>0',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Debit/Credit Note Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2 IN(70,80) and TSTF.G250=25005',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Delivery Order'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2=76',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Quotation Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2=73',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Service Form Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2=73',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Service Target Tracking'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2=73',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Service Item Tracking'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G2 IN(53,54,55,60,61,62) AND NOT CMF.ID IS NULL',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Project Costing Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'CSS.G207 IN(SELECT GID FROM SGM WHERE SID=207 AND NOT (SCC LIKE ''%F%'' OR SCC LIKE ''%C%''))',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Routine/Inspection Job Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'CSS.G207 IN(SELECT GID FROM SGM WHERE SID=207 AND (SCC LIKE ''%F%'' OR SCC LIKE ''%C%''))',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Complaint/Follow Up Job Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'Year(CSS.StartDT)<=1900 AND DateDiff(Day,GetDate(),CSS.ScheduleDT)<ISNULL((SELECT -Number FROM SYS WHERE ID=''#MISSDAYS''),0)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Missed Job Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'Year(CSS.StartDT)<=1900 AND DateDiff(Day,GetDate(),CSS.ScheduleDT)>ISNULL((SELECT -Number FROM SYS WHERE ID=''#MISSDAYS''),0)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Due Job Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G250 IN(25016,25017)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Stock Usage By Service'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G250 IN(25001,25003,25006,25007,25009,25011,25016)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Stock Receive Listing'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G250 IN(25002,25004,25005,25008,25012,25015,25017)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Stock Usage With Cost Amount'
INSERT INTO SYS (ID,Text,Number,DT) SELECT 'Rpt'+cast((GID)as varchar),'TSTF.G250 IN(25002,25004,25005,25008,25012,25015,25017)',0,NULL FROM SGM WHERE SID=40 AND [Desc]='Stock Usage'
END
