USE [ProLine]

DELETE FROM SID
INSERT INTO SID(SID,Name,Sys) VALUES(1,'System Modules',1)
INSERT INTO SID(SID,Name,Sys) VALUES(2,'TSTF Type',1)
INSERT INTO SID(SID,Name,Sys) VALUES(3,'Org. Group',0)
INSERT INTO SID(SID,Name,Sys) VALUES(4,'Currency',0)
INSERT INTO SID(SID,Name,Sys) VALUES(5,'Chart of Accounts',0)
INSERT INTO SID(SID,Name,Sys) VALUES(6,'Account Types',0)
INSERT INTO SID(SID,Name,Sys) VALUES(10,'User Roles',0)
INSERT INTO SID(SID,Name,Sys) VALUES(30,'Contact Categories',0)
INSERT INTO SID(SID,Name,Sys) VALUES(31,'Account Classification',1)
INSERT INTO SID(SID,Name,Sys) VALUES(32,'Industry',0)
INSERT INTO SID(SID,Name,Sys) VALUES(33,'Nature of Business',0)
INSERT INTO SID(SID,Name,Sys) VALUES(35,'Account Incorporation',0)
INSERT INTO SID(SID,Name,Sys) VALUES(40,'Reporting',0)
INSERT INTO SID(SID,Name,Sys) VALUES(45,'Final Account Report Type',0)
INSERT INTO SID(SID,Name,Sys) VALUES(50,'Payment Method',0)
INSERT INTO SID(SID,Name,Sys) VALUES(55,'Bank',0)
INSERT INTO SID(SID,Name,Sys) VALUES(80,'Holidays',0)
INSERT INTO SID(SID,Name,Sys) VALUES(90,'Message Templates',0)
INSERT INTO SID(SID,Name,Sys) VALUES(91,'Handy Print Formats',0)
INSERT INTO SID(SID,Name,Sys) VALUES(100,'Payment Mode',0)
INSERT INTO SID(SID,Name,Sys) VALUES(101,'Payment Terms',0)
INSERT INTO SID(SID,Name,Sys) VALUES(104,'Marital Status',0)
INSERT INTO SID(SID,Name,Sys) VALUES(108,'Country',0)
INSERT INTO SID(SID,Name,Sys) VALUES(109,'State',0)
INSERT INTO SID(SID,Name,Sys) VALUES(121,'Staff Type',0)
INSERT INTO SID(SID,Name,Sys) VALUES(123,'Remuneration Type',0)
INSERT INTO SID(SID,Name,Sys) VALUES(125,'Pay Deduction Type',0)
INSERT INTO SID(SID,Name,Sys) VALUES(126,'Pay Deduction Category',0)
INSERT INTO SID(SID,Name,Sys) VALUES(127,'Pay Deduction Locality',0)
INSERT INTO SID(SID,Name,Sys) VALUES(130,'Skill Sets',0)
INSERT INTO SID(SID,Name,Sys) VALUES(170,'Mail Merge Field',1)
INSERT INTO SID(SID,Name,Sys) VALUES(180,'Service Teams',0)
INSERT INTO SID(SID,Name,Sys) VALUES(190,'Work Status',0)
INSERT INTO SID(SID,Name,Sys) VALUES(198,'Failed Service Reason',0)
INSERT INTO SID(SID,Name,Sys) VALUES(199,'Target Status',0)
INSERT INTO SID(SID,Name,Sys) VALUES(200,'Contract Type',0)
INSERT INTO SID(SID,Name,Sys) VALUES(201,'Actions',0)
INSERT INTO SID(SID,Name,Sys) VALUES(202,'Areas',0)
INSERT INTO SID(SID,Name,Sys) VALUES(204,'Marketing Campaign',0)
INSERT INTO SID(SID,Name,Sys) VALUES(205,'Set Type',0)
INSERT INTO SID(SID,Name,Sys) VALUES(206,'Targets',0)
INSERT INTO SID(SID,Name,Sys) VALUES(207,'Service Nature',0)
INSERT INTO SID(SID,Name,Sys) VALUES(208,'Work Type',0)
INSERT INTO SID(SID,Name,Sys) VALUES(209,'UOM',0)
INSERT INTO SID(SID,Name,Sys) VALUES(210,'Company Vehicle',0)
INSERT INTO SID(SID,Name,Sys) VALUES(211,'Instruction Template',0)
INSERT INTO SID(SID,Name,Sys) VALUES(212,'Premise Type',0)
INSERT INTO SID(SID,Name,Sys) VALUES(216,'Salutation',0)
INSERT INTO SID(SID,Name,Sys) VALUES(217,'Occupation',0)
INSERT INTO SID(SID,Name,Sys) VALUES(218,'Payment Frequency',0)
INSERT INTO SID(SID,Name,Sys) VALUES(219,'Installment Method',0)
INSERT INTO SID(SID,Name,Sys) VALUES(220,'Bank / Payment Providers',0)
INSERT INTO SID(SID,Name,Sys) VALUES(223,'Customer Grading',0)
INSERT INTO SID(SID,Name,Sys) VALUES(226,'Workflow Queue',0)
INSERT INTO SID(SID,Name,Sys) VALUES(227,'Service Frequency',0)
INSERT INTO SID(SID,Name,Sys) VALUES(228,'Service Description',0)
INSERT INTO SID(SID,Name,Sys) VALUES(229,'Delivery Method',0)
INSERT INTO SID(SID,Name,Sys) VALUES(230,'Stock Type',0)
INSERT INTO SID(SID,Name,Sys) VALUES(231,'Posting Accounts Mapping',0)
INSERT INTO SID(SID,Name,Sys) VALUES(233,'Stock Costing Method',1)
INSERT INTO SID(SID,Name,Sys) VALUES(234,'Product Brands',0)
INSERT INTO SID(SID,Name,Sys) VALUES(236,'Product Specification Label',0)
INSERT INTO SID(SID,Name,Sys) VALUES(237,'Product Specification',0)
INSERT INTO SID(SID,Name,Sys) VALUES(250,'Stock Journal Type',0)
INSERT INTO SID(SID,Name,Sys) VALUES(260,'Shipping Method',0)
INSERT INTO SID(SID,Name,Sys) VALUES(270,'Zone',0)
INSERT INTO SID(SID,Name,Sys) VALUES(271,'Route',0)
INSERT INTO SID(SID,Name,Sys) VALUES(272,'Account Reconciliation Remarks',0)
INSERT INTO SID(SID,Name,Sys) VALUES(300,'Document Printing Layout',1)
INSERT INTO SID(SID,Name,Sys) VALUES(310,'Task Status',0)
INSERT INTO SID(SID,Name,Sys) VALUES(900,'Speed Date Selection',1)
